#!/usr/bin/env python
import index
import test
import search

import sys

def main():
	
	if len(sys.argv)<=1:
		sys.exit(0)

	if sys.argv[1]=="init":
		print("lets index a document directory")
		index.searchDirec()
	if sys.argv[1]=="test":
		print("lets test a small scale index and query")
		test.simpleIndex()
	if sys.argv[1]=="search":
		if(len(sys.argv)==3):
			print("Searching for %s", sys.argv[2])
			search.search(sys.argv[2])



if __name__ == '__main__':
	main()